#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VehicleApp.Droid.Resource", IsApplication=true)]

namespace VehicleApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ArrowBackIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int DoneIcon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Other = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int SelectedAccountTick = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060024
			public const int AddIcon = 2131099684;
			
			// aapt resource value: 0x7f060002
			public const int AddVehicleBackButton = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int AddVehicleHeader = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int AddVehicleLayout = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int AddVehicleMainLayout = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int AddVehicleSaveButton = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int AddVehicleToolbar = 2131099649;
			
			// aapt resource value: 0x7f060023
			public const int MainHeader = 2131099683;
			
			// aapt resource value: 0x7f060021
			public const int MainLayout = 2131099681;
			
			// aapt resource value: 0x7f060025
			public const int MainListView = 2131099685;
			
			// aapt resource value: 0x7f060022
			public const int MainToolbar = 2131099682;
			
			// aapt resource value: 0x7f060027
			public const int ViewVehicleDetailsBackButton = 2131099687;
			
			// aapt resource value: 0x7f060045
			public const int ViewVehicleDetailsButtonLayout = 2131099717;
			
			// aapt resource value: 0x7f060029
			public const int ViewVehicleDetailsMainLayout = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int ViewVehicleDetailsMake = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int ViewVehicleDetailsMakeHeader = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int ViewVehicleDetailsMakeText = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int ViewVehicleDetailsModel = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int ViewVehicleDetailsModelHeader = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int ViewVehicleDetailsModelText = 2131099695;
			
			// aapt resource value: 0x7f06003c
			public const int ViewVehicleDetailsNextService = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int ViewVehicleDetailsNextServiceHeader = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int ViewVehicleDetailsNextServiceText = 2131099710;
			
			// aapt resource value: 0x7f06003f
			public const int ViewVehicleDetailsOdometer = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int ViewVehicleDetailsOdometerHeader = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int ViewVehicleDetailsOdometerText = 2131099713;
			
			// aapt resource value: 0x7f060033
			public const int ViewVehicleDetailsRego = 2131099699;
			
			// aapt resource value: 0x7f060039
			public const int ViewVehicleDetailsRegoDue = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int ViewVehicleDetailsRegoDueHeader = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int ViewVehicleDetailsRegoDueText = 2131099707;
			
			// aapt resource value: 0x7f060034
			public const int ViewVehicleDetailsRegoHeader = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int ViewVehicleDetailsRegoText = 2131099701;
			
			// aapt resource value: 0x7f060028
			public const int ViewVehicleDetailsTitle = 2131099688;
			
			// aapt resource value: 0x7f060026
			public const int ViewVehicleDetailsToolbar = 2131099686;
			
			// aapt resource value: 0x7f060046
			public const int ViewVehicleDetailsUpdateButton = 2131099718;
			
			// aapt resource value: 0x7f060042
			public const int ViewVehicleDetailsVINPlate = 2131099714;
			
			// aapt resource value: 0x7f060043
			public const int ViewVehicleDetailsVINPlateHeader = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int ViewVehicleDetailsVINPlateText = 2131099716;
			
			// aapt resource value: 0x7f060036
			public const int ViewVehicleDetailsWOF = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int ViewVehicleDetailsWOFHeader = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int ViewVehicleDetailsWOFText = 2131099704;
			
			// aapt resource value: 0x7f060030
			public const int ViewVehicleDetailsYear = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int ViewVehicleDetailsYearHeader = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int ViewVehicleDetailsYearText = 2131099698;
			
			// aapt resource value: 0x7f060007
			public const int vehicleMakeHeader = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int vehicleMakeLayout = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int vehicleMakeText = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int vehicleModelHeader = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int vehicleModelLayout = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int vehicleModelText = 2131099659;
			
			// aapt resource value: 0x7f060019
			public const int vehicleNextServiceHeader = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int vehicleNextServiceLayout = 2131099672;
			
			// aapt resource value: 0x7f06001a
			public const int vehicleNextServiceText = 2131099674;
			
			// aapt resource value: 0x7f06001c
			public const int vehicleOdometerHeader = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int vehicleOdometerLayout = 2131099675;
			
			// aapt resource value: 0x7f06001d
			public const int vehicleOdometerText = 2131099677;
			
			// aapt resource value: 0x7f060016
			public const int vehicleRegoDueHeader = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int vehicleRegoDueLayout = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int vehicleRegoDueText = 2131099671;
			
			// aapt resource value: 0x7f060010
			public const int vehicleRegoHeader = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int vehicleRegoLayout = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int vehicleRegoText = 2131099665;
			
			// aapt resource value: 0x7f06001f
			public const int vehicleVINPlateHeader = 2131099679;
			
			// aapt resource value: 0x7f06001e
			public const int vehicleVINPlateLayout = 2131099678;
			
			// aapt resource value: 0x7f060020
			public const int vehicleVINPlateText = 2131099680;
			
			// aapt resource value: 0x7f060012
			public const int vehicleWOFLayout = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int vehicleWofHeader = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int vehicleWofText = 2131099668;
			
			// aapt resource value: 0x7f06000d
			public const int vehicleYearHeader = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int vehicleYearLayout = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int vehicleYearText = 2131099662;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AddNewVehicleLayout = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ViewVehicleDetailsLayout = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
